### ISSUE TITLE
IDictionary in Schema

### ISSUE THREAD

**Issue by bobmcallan** [mgholam/RaptorDB-Document#10]
just getting things up and running, however I have a error, which I'm not sure how to handle.

'System.Collections.Generic.IDictionary`2[System.String,System.String]', on 'RaptorDB.TypeIndexes`1[T]' violates the constraint of type 'T'. 

View

`[RegisterView]
    public class RaptorDBLogEventView : View<RaptorDBLogEvent>
    {

        public RaptorDBLogEventView()
        {
            this.Name = "LiteDBLogEventView";
            this.Description = "A primary view for LogEvent";
            this.isPrimaryList = true;
            this.isActive = true;
            this.BackgroundIndexing = true;
            this.Version = 1;

            this.Schema = typeof(RaptorDBLogEventBSchema);

            this.AddFireOnTypes(typeof(RaptorDBLogEvent));

            this.Mapper = (api, docid, doc) =>
            {
                api.Emit(docid, doc);
            };
        }
    }
`

Schema

`public class RaptorDBLogEventBSchema : RDBSchema
    {
        public Guid Id { get; set; }

        public string Message { get; set; }

        public DateTimeOffset Timestamp { get; set; }

        public LogEventLevel Level { get; set; }

        public string MessageTemplate { get; set; }

        public IDictionary<string, string> Props { get; set; }

        public Guid? CorrelationId { get; set; }

        public string Exception { get; set; }

    }`

**Comment by mgholam** [comment]
Hi Bob!

Views cannot have complex data elements like `Dictionaries` (much like normal RDB's) having such elements is usually a sign you probably need another view (e.g. master/detail).

**Comment by bobmcallan** [comment]
Thanks.
