### ISSUE TITLE
Question: Hierarcical data in view

### ISSUE THREAD

**Issue by larsbuch** [mgholam/RaptorDB-Document#14]
Is it possible to make hierarchcal data in a view?
Or if not can you make a hierarchy of views on one document?

Typically the idea of document databases is to keep the structure of the document but you have a suggested flattening of data in the views. If keeping the document structure is not possible why not just use a relational database as you still need to think normalization but just are not having the standard sql interface for querying.

I am trying to find a document database that is schemabound like yours (In my world input or output schemas still makes it schemabound). I know I need to generate the views from my json schemas. If the above hierarchy is supported I might modify so schemas are used directly.

**Comment by mgholam** [comment]
No, views are flat.
Yes, if I understand your question, you can have multiple views (flat) bound to a single document.

> If keeping the document structure is not possible why not just use a relational database as you still need > to think normalization but just are not having the standard sql interface for querying.
Please elaborate what you mean by the above.

**Comment by larsbuch** [comment]
If I want the whole document returned I need to specify in the query all the views that the document consists of in the right order like a SQL join as I cannot make a view that returns the whole document in hierarchy.

I have been watching the project and reading you blogs but it is only now I have a need for a JSON document store. I am struggeling to see if I can use your document database.

**Comment by larsbuch** [comment]
I missed that the original document store was still there (rereading was needed). Views are for in store editing and queueing. As I use a lot of querying subtrees/subdocuments in the project it seems not to be the best fit for now.

Thank you for the pointers
