### ISSUE TITLE
JSON Schema Validation?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [mgholam/RaptorDB-Document#15]
I use https://github.com/RicoSuter/NJsonSchema/ and it understand annotation attrbitues(like required, range, etc) from ComponentModel and from Newtonsoft.Json . Does raptor support validation by these? 

Thanks

**Comment by mgholam** [comment]
Any validation that you need has to be implemented in the map function for the view.

**Comment by dzmitry-lahoda** [comment]
Thanks for the answer. This database seems could be closer to the souls of JSON(ASP.NET) developers if it to understand attributes which are undresstood by ASP.NET, Newtonsoft.Json.Schema and NJsonSchema.

See for example https://docs.mongodb.com/manual/reference/operator/query/jsonSchema
