### ISSUE TITLE
System.Exception : 'Unexpectedly reached end of string' and System.Exception: Expected colon at index

### ISSUE THREAD

**Issue by frohlichcortezh** [mgholam/RaptorDB-Document#18]
I get the error when transforming the JSON returned from GetObjectHF to Object with fastJSON, but I think the error is related to raptorDB. 

Here's the stack trace : 

```
   System.Exception: Unexpectedly reached end of string
   à fastJSON.JsonParser.ParseString(Char* p, Boolean val)
   à fastJSON.JsonParser.ParseValue(Char* p, Boolean val)
   à fastJSON.JsonParser.ParseObject(Char* p)
   à fastJSON.JsonParser.ParseValue(Char* p, Boolean val)
   à fastJSON.JsonParser.ParseArray(Char* p)
   à fastJSON.JsonParser.ParseValue(Char* p, Boolean val)
   à fastJSON.JsonParser.Decode()
   à fastJSON.deserializer.ToObject(String json, Type type)
   à fastJSON.deserializer.ToObject[T](String json)
   à fastJSON.JSON.ToObject[T](String json)
```

Here's my code:

```
    public class BaseRepository<T>
    {
        protected IRaptorDB DB;
        
        public BaseRepository(IRaptorDB DB)
        {
            this.DB = DB ?? throw new ArgumentNullException(nameof(DB));
        }

        protected virtual string Key { get; } 

        public T GetObjectFromKeyStore()
        {
            IKeyStoreHF keystore = this.DB.GetKVHF();
            object o;
            if (keystore == null)
                return default(T);
            
            o = keystore.GetObjectHF(Key);
            if (o == null)
                return default(T);

            return fastJSON.JSON.ToObject<T>(o.ToString());
        }

        public bool SetObjectToKeyStore(T obj) 
        {
            IKeyStoreHF keystore = this.DB.GetKVHF();

            return keystore.SetObjectHF(Key, fastJSON.JSON.ToJSON(obj));
        }
    }
```
It happens randomly and re-writing the document without changing the JSON or deleting the DB folder and starting fresh fixes the issue, but it's not a solution.

What makes me think the problem is with RaptorDB and not fastJSON is that to me it's seems that the string returned by GetObjectHF is badly formatted.
Here's an example of a string that gives this error:
"[{\"$type\":\"domaine.Engin, domaine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\",
	\"XXXFIELD\":\"XXXX\\\\483deeab-1ce8-4c79-b45f-588785e0e1e4\",\"Codes\":\"S50\",\"Nom\":\"XNON  \",\"CodeDepot\":null,\"Marqueurs\":\"\",
	\"Description\":\"S50 - MINIPELLE CATERPILLAR PAYEN  \",\"Code\":\"S50\",\"RessourceOid\":1139,\"PlanningXXXFIELD\":null},{\"$type\":\"domaine.Engin, domaine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nu潬祲itaux \",\"Adresse\":\"\"},
{\"$type\":\"1\",\"XXXFIELD\":\"XXXX\\\\f704e193-95b5-4bc2-b427-115dbf5affac\",\"Code\":\"530007\",\"Nom\":\"530007 Chantiers \0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"

There are many more \0\0 in the end, I excluded to make it more readable.

```
System.Exception: Expected colon at index 29340
   à fastJSON.JsonParser.ParseObject(Char* p)
   à fastJSON.JsonParser.ParseValue(Char* p, Boolean val)
   à fastJSON.JsonParser.ParseArray(Char* p)
   à fastJSON.JsonParser.ParseValue(Char* p, Boolean val)
   à fastJSON.JsonParser.Decode()
   à fastJSON.deserializer.ToObject(String json, Type type)
   à fastJSON.deserializer.ToObject[T](String json)
   à fastJSON.JSON.ToObject[T](String json)
```
This is a related error that happens randomly but again, the JSON returned seems to be badly formatted.

"[{\"$type\":\"domaine.Engin, domaine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\",\"XXXField\":\"XXXXX\\\\483deeab-1ce8-4c79-b45f-588785e0e1e4\",\"Codes\":\"S50\",\"Nom\":\"MINIPELLE CATERPILLAR PublicKeyToken=null\",\"XXXField\":\"XXXXX\\\\49b3598a-fca5-43df-b262-7bc4eb9fb120\",\"C"

I'd love some help. 
Thank you in advance.

**Comment by mgholam** [comment]
How big is the json object string?

**Comment by frohlichcortezh** [comment]
I have 3 documents and the error has occurred on the 3 at different times:

- "[{\"$type\":\"domaine.Collaborateur, domaine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\",
Around 12k characters

- "[{\"$types\":{\"domaine.Chantier, domaine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\":\"1\"},\"$type\":\"1\",\"
Around 30k characters

- "[{\"$type\":\"domaine.Engin, domaine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\"
Around 28k characters

I'm using version 4.0.9 from nuget and my project compiles to netstandard and netframework
```
<PropertyGroup>
    <TargetFrameworks>net461;netstandard2.0</TargetFrameworks>
</PropertyGroup>
```

**Comment by mgholam** [comment]
And is your db shutting down properly after saves?

**Comment by frohlichcortezh** [comment]
I use DB.Shutdown() when app is closed.

**Comment by mgholam** [comment]
Is the problem time or number of inserts based?

**Comment by mgholam** [comment]
I will write a test to insert and read multiple large objects to the HF store and let you know.

**Comment by frohlichcortezh** [comment]
I haven't found a relation to when the problem happens. 
I write the documents in the beggining of the day and only read them througout the day.
At some point, I get the error when reading the DB, but I haven't changed it.

I'll start fresh today and send logs later on if/when the problem happens.

Thank you very much for your help, I really appreciate it.

**Comment by frohlichcortezh** [comment]
And if you need any other information, please let me know.

**Comment by mgholam** [comment]
... ok, so you write the all the docs at the start, and only read docs until failure? absolutely no more writes during the day?

**Comment by frohlichcortezh** [comment]
Not absolutely, it can happen here and there, but it's mainly reading to these documents.

I do writes though on another view, using DB.Save().

**Comment by mgholam** [comment]
Ok, the problem is in reading multiple HF pages (invalid refs somehow), the cause could be when flushing free page list to disk, or page ref mangling... 

Hopefully the test will show.

**Comment by frohlichcortezh** [comment]
Here's how I set it up:

```
            Global.RequirePrimaryView = false;
            local.RegisterView(new ChantierView());
            local.RegisterView(new CollaborateurView());
            local.RegisterView(new EnginView());
            local.RegisterView(new MouvementView())
```

**Comment by mgholam** [comment]
The HF storage file is independent to the view storage.

**Comment by mgholam** [comment]
Have you tried:
```
return keystore.SetObjectHF(Key, obj); //fastJSON.JSON.ToJSON(obj));
```

**Comment by frohlichcortezh** [comment]
Just tried but couldn't easily convert the object returned from GetObjectHF, since I'm using generics.
If you think it could solve the problem I can try refactoring to use it this way.

**Comment by mgholam** [comment]
Ah I see. 
My test is running until it breaks...

**Comment by mgholam** [comment]
Is your app running in IIS?

**Comment by frohlichcortezh** [comment]
No, it's an winform app, but I recover the data I insert in the documents from a WebService running on IIS.

**Comment by frohlichcortezh** [comment]
Strange thing happened. 
App was running with no issues. 
You've talked about IIS, so I did what I do a couple of times a day, I restarted IIS with a new version of the webservice and then I got the error. 

RaptorDB log is on pastebin : https://pastebin.com/MQnLzi3T

Tried to reproduce but couldn't.

**Comment by mgholam** [comment]
It seems `RaptorDB` is not shutting down properly.

**Comment by mgholam** [comment]
I can't reproduce the problem so far with the following code:
```c#
private void HFTest()
{
    var hf = rap.GetKVHF();
    var r = new Random();

    if (hf.CountHF() == 0)
    {
        hf.SetObjectHF("1", Faker.TextFaker.Sentences(r.Next(200) + 10) + "1");
        hf.SetObjectHF("2", Faker.TextFaker.Sentences(r.Next(200) + 10) + "2");
        hf.SetObjectHF("3", Faker.TextFaker.Sentences(r.Next(200) + 10) + "3");
        hf.SetObjectHF("4", Faker.TextFaker.Sentences(r.Next(200) + 10) + "4");
    }

    int j = 0;
    while (j++ < 10000)
    {
        //rap.FreeMemory();
        var k = (r.Next(3) + 1).ToString();
        if (j % 10 == 0)
        {
            hf.SetObjectHF(k, Faker.TextFaker.Sentences(r.Next(200) + 200) + k);
        }
        k = (r.Next(3) + 1).ToString();
        var o = hf.GetObjectHF(k);
        if ((o as string).EndsWith(k) == false)
            throw new Exception("invalid data");
        stsError.Text = "j = " + j;
        Application.DoEvents();
        Thread.Sleep(1000);
    }
    // 
}

```

**Comment by frohlichcortezh** [comment]
Ok, I've changed the way I shutdown the DB. 
I'll see if there are any changes.

**Comment by mgholam** [comment]
How you doing?

**Comment by frohlichcortezh** [comment]
Got stucked with other stuff and couldn't test the app today. Should get back full time to it Monday or Tuesday and let you know.

**Comment by frohlichcortezh** [comment]
I think the problem is related to the DB not shutting down properly. 
I'm closing the issue and will keep looking.
Thank you very much for your help.
