### ISSUE TITLE
Large Large files

### ISSUE THREAD

**Issue by mohammadomt** [mgholam/RaptorDB-Document#9]
I was testing RaptorDB using the sample code, codes are really easy to write (than couchbase) but after running test I found out that database stored about 200MB on the disk. I tried a compression with WinRar and it compressed data to 4MB(!). This means that a huge part of it is just being repeated.
I think something must be changed in saving mechanism.

**Comment by mgholam** [comment]
Compression ans speed are a trade-off, `RaptorDB` goes for speed.
